[key]
ali_nls_app_key = rEs56rswzWQqXy14
ali_nls_key_id = LTAI5tMogoxLgENvSKMHuYbz
ali_nls_key_secret = xe3JLfxTvSksO5RkFZpAMzKMl6iAiM
ali_tss_app_key = rEs56rswzWQqXy14
ali_tss_key_id = LTAI5tMogoxLgENvSKMHuYbz
ali_tss_key_secret = xe3JLfxTvSksO5RkFZpAMzKMl6iAiM
asr_mode = ali
baidu_emotion_api_key = 
baidu_emotion_app_id = 
embedding_api_model = text-embedding-v3
fay_url = http://127.0.0.1:5000
gpt_api_key = sk-c9b8659683a541bfaa8580448ca67766
gpt_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1
gpt_model_engine = qwen-plus
local_asr_ip = 127.0.0.1
local_asr_port = 10197
ltp_mode = baidu
ms_tts_key = 
ms_tts_region = 
proxy_config = 
start_mode = web
tts_module = ali
volcano_tts_access_token = 
volcano_tts_appid = 
volcano_tts_cluster = 
volcano_tts_voice_type = 

