version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: football_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cd
      MYSQL_DATABASE: football_league
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
