[key]
gpt_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1
gpt_api_key = sk-c9b8659683a541bfaa8580448ca67766
gpt_model_engine = qwen-plus
embedding_api_model = text-embedding-v3
baidu_emotion_api_key =
baidu_emotion_secret_key =
tts_module = ms
ASR_mode = none
ali_tss_key_id = LTAI5tAH8QgghqZMq2YeGwyX
ali_tss_key_secret = FKozOttONluIeEyUDlBcThxBcBOBoJ
ali_tss_app_key = Fkdu8QgcBHvCUIsn
ali_nls_key_id = LTAI5tAH8QgghqZMq2YeGwyX
ali_nls_key_secret = FKozOttONluIeEyUDlBcThxBcBOBoJ
ali_nls_app_key = Fkdu8QgcBHvCUIsn

[ali_nls]
app_key = Fkdu8QgcBHvCUIsn
access_key_id = LTAI5tAH8QgghqZMq2YeGwyX
access_key_secret = FKozOttONluIeEyUDlBcThxBcBOBoJ

[server]
fay_url = http://127.0.0.1:5100
start_mode = web
